### ISSUE TITLE
`make clibs` errors with `spec/compiler/ise/egl: No such file or directory.`

### ISSUE THREAD

**Issue by proehlen** [pacoispaco/eifogl#1]
Sorry I'm very much an Eiffel/OpenGL/C-programming noob and I'm having the above problem when trying to follow the instructions in the README and I can't work it out.

Output from `make clibs`:

```
make -C spec/compiler/ise/egl
make[1]: *** spec/compiler/ise/egl: No such file or directory.  Stop.
Makefile:34: recipe for target 'spec/compiler/ise/egl' failed
make: *** [spec/compiler/ise/egl] Error 2
```

I can't find the `spec/compiler/ise` folder in my cloned version of the repo.

My environment variables have been set correctly per the readme as near as I can tell.

**Comment by pacoispaco** [comment]
Thanks for the issue report. Sorry for a very late reply.

I've corrected the path in the Makefile and also in the .ecf file for eglut which also was incorrect.

You should still get 9 warnings ("warning: multi-character character constant [-Wmultichar]") when compiling eglut.lib but it will compile and work. I haven't got time now to fix the warnings.
